### ISSUE TITLE
Please export EditorConfiguration

### ISSUE THREAD

**Issue by domehead100** [atassis/react-codemirror-ts#5]
The options for Codemirror is of type EditorConfiguration.

This type is not exported so when using the component options comes up as "any" type, thus intellisense/autocomplete is not available to see the available types in the editor (e.g., vscode).

A fix is to change "declare type CodemirrorProps" in index.d.ts to "export declare type CodemirrorProps", or in other words export the type for the options from the es module.

Thanks.

**Comment by atassis** [comment]
Haven't seen this during the weekend, will deploy a fix in a couple of days

**Comment by atassis** [comment]
So the `EditorConfiguration` is imported from `@types/codemirror', no need of double exporting it from this repo
